# Generated by Django 5.1.2 on 2024-11-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0006_alter_bike_bikeimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bike',
            new_name='Vehicles',
        ),
    ]
