# Generated by Django 5.1.2 on 2024-10-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeName', models.CharField(max_length=200)),
                ('frontTyrePressure', models.CharField(max_length=50)),
                ('backTyrePressure', models.CharField(max_length=50)),
                ('frontTyreSize', models.CharField(max_length=50)),
                ('backTyreSize', models.CharField(max_length=50)),
            ],
        ),
    ]
