# Generated by Django 5.1.2 on 2024-10-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0004_alter_bike_bikeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikeImage',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
