# Generated by Django 5.1.2 on 2024-11-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0007_rename_bike_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='bikeImage',
            new_name='VehicleImage',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='bikeName',
            new_name='vehicleName',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vehicleType',
            field=models.CharField(default='Unknown', max_length=200, null=True),
        ),
    ]
