# Generated by Django 5.1.2 on 2024-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0008_rename_bikeimage_vehicles_vehicleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicleType',
            field=models.CharField(max_length=200),
        ),
    ]
