# Generated by Django 5.1.2 on 2025-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0011_indiabikedatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('usergmail', models.CharField(blank=True, db_column='usergmail', max_length=255, null=True)),
                ('vehicletype', models.CharField(blank=True, db_column='vehicletype', max_length=100, null=True)),
                ('id', models.CharField(blank=True, db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('user_mileage', models.IntegerField(blank=True, db_column='user_mileage', null=True)),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
    ]
