# Generated by Django 5.1.2 on 2025-02-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEnd', '0012_userdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearchedCar',
            fields=[
                ('id', models.CharField(db_column='id', max_length=100, primary_key=True, serialize=False)),
                ('make', models.CharField(db_column='Make', max_length=100)),
                ('model', models.CharField(db_column='Model', max_length=100)),
                ('image_url', models.TextField(db_column='Image_URL')),
                ('price', models.IntegerField(db_column='Price')),
                ('count', models.IntegerField(db_column='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'popular_searched_cars',
                'managed': False,
            },
        ),
    ]
